export const delimiter = ':';

export function toMessageWithCode(code: string, msg?: string): string {
  return `${code}${delimiter} ${msg ?? ''}`;
}

export const EMAIL_ALREADY_TAKEN = 'EMAIL_ALREADY_TAKEN';
export const PHONE_DUPLICATION = 'PHONE_DUPLICATION';
export const LINK_DUPLICATION = 'AFFILIATE_LINK_DUPLICATION';

export const DOMAIN_VALIDATION_FAIL = 'DOMAIN_VALIDATION_FAIL';
export const PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH';
export const USER_NOT_EXIST = 'USER_NOT_EXIST';
export const PRODUCT_NOT_EXIST = 'PRODUCT_NOT_EXIST';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

export const TOKEN_NOT_EXIST = 'TOKEN_NOT_EXIST';

export const INVALID_CARD_INFO = 'INVALID_CARD_INFO';
export const UNEXPECTED_ERROR_AT_BILLING_SERVICE = 'UNEXPECTED_ERROR_AT_BILLING_SERVICE';
export const INSUFFICIENT_CARD_CREDIT = 'INSUFFICIENT_CARD_CREDIT';

export const ACTIVE_STYLING_ORDER_EXISTS = 'ACTIVE_STYLING_ORDER_EXISTS';
export const ACTIVE_ONLINE_STYLING_ORDER_EXISTS = 'ACTIVE_ONLINE_STYLING_ORDER_EXISTS';

export const CARD_INFO_CHANGE_ON_DELIVERY = 'CARD_INFO_CHANGE_ON_DELIVERY';

export const DELIVERING_ORDER_EXIST = 'DELIVERING_ORDER_EXIST';
export const ALREADY_RETURN_BOX_ORDER_DELIVERED = 'ALREADY_RETURN_BOX_ORDER_DELIVERED';
export const NOT_RETURN_BOX = 'NOT_RETURN_BOX';
