name: Build / Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD:
          POSTGRES_DB: selectchu_test
        ports:
        - 5432:5432
          # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Cache
      id: cache
      uses: actions/cache@v1.0.3
      with:
        path: build-cache
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: setup test env
      run: npx nps ci.pretest

    - name: npm build, and test
      run: |
        yarn build
        yarn test

    - name: slack notification
      uses: 8398a7/action-slack@v2
      if: always()
      with:
        status: ${{ job.status }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
